Traceback (most recent call last):
  File "/home/open/work/src/core/setup.py", line 1, in <module>
    from setuptools import find_packages, setup
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.10/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2128, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2591, in from_location
    )._reload_version()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2989, in _reload_version
    md_version = self._get_version()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2770, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2554, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1417, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/open/work/install/control/lib/python3.10/site-packages/control-0.0.0-py3.10.egg-info/PKG-INFO'
